version: '3.8'

services:
  symfony:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: "mysql://uzvfure5wlfktzc2:CphBsMVxuRKQUevyWbkP@b60iositjqcste4mia4e-mysql.services.clever-cloud.com:3306/b60iositjqcste4mia4e"
